groups:
  - name: general
    rules:
      - alert: Watchdog
        expr: vector(1)
        labels:
          severity: dogshit
      - alert: Up
        expr: up == 0
        for: 20s
        labels:
          severity: high
        annotations:
          summary:
            Prometheus job "{{ $labels.job }}" with "{{ $labels.instance }}" instance is down
  - name: example
    rules:
      - record: example_requests_percentage_200
        expr: 100 * sum(example_requests_total{status_code="200"}) / sum(example_requests_total)
      - record: example_requests_percentage_400
        expr: 100 * sum(example_requests_total{status_code=~"404|418"}) / sum(example_requests_total)
      - record: example_requests_percentage_500
        expr: 100 * sum(example_requests_total{status_code=~"5.."}) / sum(example_requests_total)
      - record: example_requests_duration_200ms_bucket_percentage
        expr: 100 * (1 - example_request_duration_seconds_bucket{le="0.2"} / ignoring(le) example_request_duration_seconds_bucket{le="+Inf"})
